### ISSUE TITLE
Compilation pipeline breakage

### ISSUE THREAD

**Issue by pandeiro** [adzerk-oss/boot-cljs-example#7]
When developing with the pipeline recommended in the README, ie:

```clojure
  (comp (serve :port 8080 :dir "target")
        (watch)
        (speak)
        (reload)
        (cljs-repl)
        (cljs :source-map    true
              :unified-mode  true
              :optimizations :advanced))
```

...there is a recurring Exception being thrown that breaks the pipeline, which must then be restarted. The Exception looks like this on my machine:

```
Exception in thread "Thread-31" java.nio.file.NoSuchFileException: /home/mu/.boot/tmp/home/mu/repos/com/github/adzerk/boot-cljs-example/29x/-p9hf6h/frontend
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by myguidingstar** [comment]
We've got newer boot-cljs now
